
services:
    ftven.oaipmh.ruler:
        class: Ftven\Bundle\OaiPmhServerBundle\OaiPmh\OaiPmhRuler
        calls:
            - [ setCountPerLoad, [ '%ftven.oaipmh_server.count_per_load%' ] ]

    ftven.oaipmh.twig.record_extension:
        class: Ftven\Bundle\OaiPmhServerBundle\Twig\RecordExtension
        calls:
            - [ setDataProvider, [ "@ftven.oaipmh.data_provider" ] ]
        tags:
            - { name: twig.extension }

    ftven.oaipmh.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ["@=service('kernel').getCacheDir()"]
